<template>
  <div>
    <Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col align="left" fixed="left">
          巴歇尔槽型号：
          <el-select v-model="value" size="small" placeholder="请选择">
            <el-option
              v-for="item in metype"
              :key="item.value"
              :label="item.label"
              :value="item.value">
            </el-option>
          </el-select>
        </Col>
        <Col>
          <Input search enter-button suffix="ios-search" placeholder="请输入站名：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="form.searchmsg" />
        </col>
        <Col>
          <Button type="primary" style="width: auto;margin-right: 20px;" @click="err">详细信息</Button>
        </col>
      </Row>
      <Row class="fgline"></Row>
      <el-table
        :data="tabledata"
        border
        :height="theight"
        v-loading="loading"
        style="width: 100%"
        @cell-click="cellclick"
        @sort-change="sort_change">
        <el-table-column
          label=" "
          prop="ROWID"
          align="center"
          width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="站名"
          prop="STNM"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="渠道"
          prop="CANAL_CODE"
          align="center"
          min-width="120"
         >
        </el-table-column>
        <el-table-column
          label="巴歇尔槽型号"
          prop="MODEL"
          align="center"
          min-width="160"
         >
        </el-table-column>
        <el-table-column
          label="最大水深(m)"
          prop="Z_MAX"
          align="center"
          min-width="150"
         >
        </el-table-column>
        <el-table-column
          label="最大流量(m³/s)"
          prop="Q_MAX"
          align="center"
          min-width="150"
          >
        </el-table-column>
        <el-table-column
          label="备注"
          prop="MEMO"
          align="center"          
          min-width="160">
        </el-table-column>
      </el-table>     
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        theight:window.innerHeight-202,
        metype:
        [
          {
            value:'0',
            label:'所有类型',
          },
          {
            value:'1',
            label:'1号',
          },
          {
            value:'2',
            label:'2号', 
          },
          {
            value:'3',
            label:'3号', 
          },
          {
            value:'4',
            label:'4号', 
          },
          {
            value:'5',
            label:'5号',
          },
          {
            value:'6',
            label:'6号', 
          },
          {
            value:'7',
            label:'7号', 
          },
          {
            value:'8',
            label:'8号', 
          },
          {
            value:'9',
            label:'9号', 
          },
          {
            value:'10',
            label:'10号', 
          },
          {
            value:'11',
            label:'11号',
          },
          {
            value:'12',
            label:'12号', 
          },
          {
            value:'13',
            label:'13号', 
          },
          {
            value:'14',
            label:'14号', 
          },
          {
            value:'15',
            label:'15号',
          },
          {
            value:'16',
            label:'16号', 
          },
          {
            value:'17',
            label:'17号', 
          },
          {
            value:'18',
            label:'18号', 
          },
          {
            value:'19',
            label:'19号', 
          },
          {
            value:'20',
            label:'20号', 
          },
          {
            value:'21',
            label:'21号',
          },
          {
            value:'22',
            label:'22号', 
          },
          {
            value:'23',
            label:'23号', 
          },
          {
            value:'24',
            label:'24号', 
          },
          {
            value:'25',
            label:'25号',
          },
        ],
        tabledata:
        [
          {
            ROWID:'1',
            STNM:'英雄渠首站',
            CANAL_CODE:'英雄支渠',
            MODEL:'9号',
            Z_MAX:'0.75',
            Q_MAX:'0.85',
            MEMO:'',
          },
          {
            ROWID:'2',
            STNM:'姥姥窝渠首站',
            CANAL_CODE:'姥姥窝支渠',
            MODEL:'9号',
            Z_MAX:'0.75',
            Q_MAX:'0.85',
            MEMO:'',
          },
          {
            ROWID:'3',
            STNM:'大坪渠首站',
            CANAL_CODE:'大坪支渠',
            MODEL:'9号',
            Z_MAX:'0.75',
            Q_MAX:'0.85',
            MEMO:'',
          },
          {
            ROWID:'4',
            STNM:'阮家冲渠首站',
            CANAL_CODE:'阮家冲支渠',
            MODEL:'9号',
            Z_MAX:'0.75',
            Q_MAX:'0.85',
            MEMO:'',
          },
          {
            ROWID:'5',
            STNM:'徐家冲站',
            CANAL_CODE:'徐家冲支渠',
            MODEL:'9号',
            Z_MAX:'0.75',
            Q_MAX:'0.85',
            MEMO:'',
          },
        ],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
  }
</script>