<template>
  <div>
    <Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col align="left" fixed="left">
          水闸类型：
          <el-select v-model="value" size="small" placeholder="请选择">
            <el-option
              v-for="item in metype"
              :key="item.value"
              :label="item.label"
              :value="item.value">
            </el-option>
          </el-select>
        </Col>
        <Col>
          <Input search enter-button suffix="ios-search" placeholder="请输入站名：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="form.searchmsg" />
        </col>
        <Col>
          <Button type="primary" style="width: auto;margin-right: 20px;" @click="err">详细信息</Button>
        </col>
      </Row>
      <Row class="fgline"></Row>
      <el-table
        :data="tabledata"
        border
        :height="theight"
        v-loading="loading"
        style="width: 100%"
        @cell-click="cellclick"
        @sort-change="sort_change">
        <el-table-column
          label=" "
          prop="ROWID"
          align="center"
          width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="站名"
          prop="STNM"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="所在渠道"
          prop="CANAL_CODE"
          align="center"
          min-width="120"
          >
        </el-table-column>
        <el-table-column
          label="水闸类型"
          prop="SLTP"
          align="center"
          min-width="100"
          >
        </el-table-column>
        <el-table-column
          label="水闸宽度"
          prop="GTHLNTWD"
          align="center"
          min-width="80"
          >
        </el-table-column>
        <el-table-column
          label="最大开度"
          prop="GATE_HI"
          align="center"
          min-width="100"
          >
        </el-table-column>
        <el-table-column label="闸前" align="center">
          <el-table-column
            label="最大水深"
            prop="Z_MAX_F"
            align="center"
            min-width="100"
            >
          </el-table-column>
          <el-table-column
            label="最大流量"
            prop="Q_MAX_F"
            align="center"
            min-width="100"
            >
          </el-table-column>
        </el-table-column>
        <el-table-column label="闸后" align="center">
          <el-table-column
            label="最大水深"
            prop="Z_MAX_B"
            align="center"
            min-width="100"
            >
          </el-table-column>
          <el-table-column
            label="最大流量"
            prop="Q_MAX_B"
            align="center"
            min-width="100"
            >
          </el-table-column>  
        </el-table-column>        
      </el-table>
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        theight:window.innerHeight-202,
        metype:
        [
          {
            value:'0',
            label:'所有类型',
          },
          {
            value:'1',
            label:'引水闸',
          },
          {
            value:'2',
            label:'分水闸', 
          },
          {
            value:'3',
            label:'泄洪闸', 
          },
          {
            value:'4',
            label:'节制闸', 
          },
          {
            value:'5',
            label:'冲沙闸',
          },
          {
            value:'6',
            label:'退水闸', 
          },
          {
            value:'9',
            label:'其他', 
          },
        ],
        tabledata:
        [
          {
            ROWID:'1',
            STNM:'总干渠渠首站',
            CANAL_CODE:'总干渠',
            SLTP:'泄洪闸',
            GTHLNTWD:'4.0',
            GATE_HI:'5.0',
            Z_MAX_F:'',
            Q_MAX_F:'',
            Z_MAX_B:'',
            Q_MAX_B:'',
          },
          {
            ROWID:'2',
            STNM:'峡山干渠站',
            CANAL_CODE:'峡山干渠',
            SLTP:'泄洪闸',
            GTHLNTWD:'2.0',
            GATE_HI:'1.9',
            Z_MAX_F:'1.5',
            Q_MAX_F:'',
            Z_MAX_B:'',
            Q_MAX_B:'',
          },
          {
            ROWID:'3',
            STNM:'南岭站',
            CANAL_CODE:'总干渠',
            SLTP:'泄洪闸',
            GTHLNTWD:'2.2',
            GATE_HI:'4.0',
            Z_MAX_F:'1.5',
            Q_MAX_F:'',
            Z_MAX_B:'',
            Q_MAX_B:'',
          },
          {
            ROWID:'4',
            STNM:'养鱼塘站',
            CANAL_CODE:'总干渠',
            SLTP:'泄洪闸',
            GTHLNTWD:'2.0',
            GATE_HI:'3.5',
            Z_MAX_F:'1.5',
            Q_MAX_F:'',
            Z_MAX_B:'',
            Q_MAX_B:'',
          },
        ],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
  }
</script>