<template>
  <div>
    <Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col align="left" fixed="left">
          测量类型：
          <el-select v-model="value" size="small" placeholder="请选择">
            <el-option
              v-for="item in metype"
              :key="item.value"
              :label="item.lable"
              :value="item.value">
            </el-option>
          </el-select>
        </Col>
        <Col>
        <!--姓名模糊查询 -->
          <Input search enter-button suffix="ios-search" placeholder="站点名称：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="searchmsg" />
        </Col>
        <Col> 
           <Button type="primary" style="width: auto;margin-right: 20px;" @click="err">导出</Button>
        </Col>
        </Row>
        <Row class="fgline"></Row> 
        <el-table
          :data="tabledata"
          border
          :height="theight"
          v-loading="loading"
          style="width: 100%"
          @cell-click="cellclick"
          @sort-change="sort_change"
        >
          <el-table-column
            label=" "
            prop="ROWID"
            align="center"
            width="65"
            fixed="left">
          </el-table-column>
          <el-table-column
            prop="STNM"
            label="站名"
            align="center"
            fixed="left"
            sortable
            min-width="130">
          </el-table-column>
          <el-table-column
            prop="Canal_Name"
            label="渠道"
            align="center"
            fixed="left"
            sortable
            min-width="130">
          </el-table-column>
          <el-table-column
            prop="ME_TYPE"
            label="测量类型"
            align="center"
            fixed="left"
            sortable
            min-width="100">
          </el-table-column>
          <el-table-column
            prop="RS_COUNT"
            label="率定设定次数"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="100">
          </el-table-column>
          <el-table-column
            prop="END_COUNT"
            label="完成次数"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="100">
          </el-table-column>
          <el-table-column
            prop="Postion"
            label="站址"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="180">
          </el-table-column>
          <el-table-column
            prop="MEMO"
            label="备注"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="180">
          </el-table-column>
        </el-table> 
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        theight:window.innerHeight-282,
        metype:[ 
        {
          lable:'所有站点',
          value:'0',
        },
        {
          lable:'标准断面',
          value:'1',
        },
        {
          lable:'巴歇尔槽',
          types:'2',
        },
        {
          lable:'水闸',
          value:'3',
        },],
        tabledata:
        [
          {
            ROWID:'1',
            STNM:'黄龙站',
            Canal_Name:'黄龙支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'回龙铺镇金玉村',
            MEMO:'',
          },
          {
            ROWID:'2',
            STNM:'四清站',
            Canal_Name:'四清支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡太平山村',
            MEMO:'',
          },
          {
            ROWID:'3',
            STNM:'八一站',
            Canal_Name:'八一支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡涌泉村',
            MEMO:'',
          },
          {
            ROWID:'4',
            STNM:'青林站',
            Canal_Name:'青林支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡涌泉村',
            MEMO:'',
          },
          {
            ROWID:'5',
            STNM:'仁寿站',
            Canal_Name:'仁寿支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'煤炭坝镇砖塘村',
            MEMO:'',
          },
          {
            ROWID:'6',
            STNM:'金塘站',
            Canal_Name:'金塘支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'煤炭坝镇富家村',
            MEMO:'',
          },
          {
            ROWID:'7',
            STNM:'P4支渠站',
            Canal_Name:'P4支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇檀树湾村',
            MEMO:'',
          },
          {
            ROWID:'8',
            STNM:'P5支渠站',
            Canal_Name:'P5支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇檀树湾村',
            MEMO:'',
          },
          {
            ROWID:'9',
            STNM:'一排支渠站',
            Canal_Name:'一排渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇新乡村',
            MEMO:'',
          },
          {
            ROWID:'10',
            STNM:'二排支渠站',
            Canal_Name:'一排渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇新乡村',
            MEMO:'',
          },
          {
            ROWID:'11',
            STNM:'五支渠站',
            Canal_Name:'五支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇双清村',
            MEMO:'',
          },
          {
            ROWID:'12',
            STNM:'三排支渠站',
            Canal_Name:'三排渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇双清村',
            MEMO:'',
          },
          {
            ROWID:'13',
            STNM:'四排支渠站',
            Canal_Name:'死排渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇双清村',
            MEMO:'',
          },
          {
            ROWID:'14',
            STNM:'姚家台',
            Canal_Name:'姚家台支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄材镇沙坪村',
            MEMO:'',
          },
          {
            ROWID:'15',
            STNM:'檀树湾泵站',
            Canal_Name:'檀树湾支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇檀树湾村',
            MEMO:'',
          },
          {
            ROWID:'16',
            STNM:'南干渠首',
            Canal_Name:'南干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'箐华铺乡桃林桥村',
            MEMO:'',
          },
          {
            ROWID:'17',
            STNM:'北干渠首',
            Canal_Name:'北干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'箐华铺乡桃林桥村',
            MEMO:'',
          },
          {
            ROWID:'18',
            STNM:'毛栗站',
            Canal_Name:'煤衡干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'煤炭坝镇贺石桥村',
            MEMO:'',
          },
          {
            ROWID:'19',
            STNM:'九支沟站',
            Canal_Name:'九支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双江口镇双清村',
            MEMO:'',
          },
          {
            ROWID:'20',
            STNM:'新塘站',
            Canal_Name:'总干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡神武村',
            MEMO:'',
          },
          {
            ROWID:'21',
            STNM:'砖塘流量站',
            Canal_Name:'砖塘支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'煤炭坝镇砖塘村',
            MEMO:'',
          },
          {
            ROWID:'22',
            STNM:'煤炭坝流量站',
            Canal_Name:'总干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'煤炭坝镇富家村',
            MEMO:'',
          },
          {
            ROWID:'23',
            STNM:'陡坡流量站',
            Canal_Name:'陡坡支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'煤炭坝镇富家村',
            MEMO:'',
          },
          {
            ROWID:'24',
            STNM:'太阳流量站',
            Canal_Name:'太阳干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'大陈桥镇玉新村',
            MEMO:'',
          },
          {
            ROWID:'25',
            STNM:'回龙铺流量站',
            Canal_Name:'回龙铺支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'回龙铺镇回龙铺村',
            MEMO:'',
          },
          {
            ROWID:'26',
            STNM:'天鹅流量站',
            Canal_Name:'天鹅支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'回龙铺镇回龙铺村',
            MEMO:'',
          },
          {
            ROWID:'27',
            STNM:'胜溪站',
            Canal_Name:'胜溪支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄材镇石狮庵村',
            MEMO:'',
          },
          {
            ROWID:'28',
            STNM:'白茹山站',
            Canal_Name:'白茹山支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄材镇石山村',
            MEMO:'',
          },
          {
            ROWID:'29',
            STNM:'松华站',
            Canal_Name:'松华支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄材镇沩滨村',
            MEMO:'',
          },
          {
            ROWID:'30',
            STNM:'谢家冲站',
            Canal_Name:'谢家冲支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'横市镇利民村',
            MEMO:'',
          },
          {
            ROWID:'31',
            STNM:'茅栗站',
            Canal_Name:'茅栗支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'双凫镇双明村',
            MEMO:'',
          },
          {
            ROWID:'32',
            STNM:'湖溪站',
            Canal_Name:'湖溪支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡湖溪塘村',
            MEMO:'',
          },
          {
            ROWID:'33',
            STNM:'向前站',
            Canal_Name:'向前支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡湖溪塘村',
            MEMO:'',
          },
          {
            ROWID:'34',
            STNM:'白竹站',
            Canal_Name:'白竹支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'菁华铺乡嶂山村',
            MEMO:'',
          },
          {
            ROWID:'35',
            STNM:'总干泄洪闸站',
            Canal_Name:'总干渠',
            ME_TYPE:'水闸',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄材镇石狮庵村',
            MEMO:'',
          },
          {
            ROWID:'36',
            STNM:'峡山泄洪闸站',
            Canal_Name:'峡山干渠',
            ME_TYPE:'水闸',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡泉龙村',
            MEMO:'',
          },
          {
            ROWID:'37',
            STNM:'南岭泄洪闸站',
            Canal_Name:'总干渠',
            ME_TYPE:'水闸',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'喻家坳乡南岭村',
            MEMO:'',
          },
          {
            ROWID:'38',
            STNM:'养鱼塘泄洪闸站',
            Canal_Name:'总干渠',
            ME_TYPE:'水闸',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'菁华铺乡菁华铺村',
            MEMO:'',
          },
          
        ],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
  }
</script>