<template>
  <div>
    <Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col align="left" fixed="left">
          测量类型：
          <el-select v-model="value" size="small" placeholder="请选择">
            <el-option
              v-for="item in metype"
              :key="item.value"
              :label="item.lable"
              :value="item.value">
            </el-option>
          </el-select>
        </Col>
        <Col>
        <!--姓名模糊查询 -->
          <Input search enter-button suffix="ios-search" placeholder="站点名称：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="searchmsg" />
        </Col>
        <Col> 
           <Button type="primary" style="width: auto;margin-right: 20px;" @click="err">导出</Button>
        </Col>
        </Row>
        <Row class="fgline"></Row> 
        <el-table
          :data="tabledata"
          border
          :height="theight"
          v-loading="loading"
          style="width: 100%"
          @cell-click="cellclick"
          @sort-change="sort_change"
        >
          <el-table-column
            label=" "
            prop="ROWID"
            align="center"
            width="65"
            fixed="left">
          </el-table-column>
          <el-table-column
            prop="STNM"
            label="站名"
            align="center"
            fixed="left"
            sortable
            min-width="130">
          </el-table-column>
          <el-table-column
            prop="Canal_Name"
            label="渠道"
            align="center"
            fixed="left"
            sortable
            min-width="130">
          </el-table-column>
          <el-table-column
            prop="ME_TYPE"
            label="测量类型"
            align="center"
            fixed="left"
            sortable
            min-width="100">
          </el-table-column>
          <el-table-column
            prop="RS_COUNT"
            label="率定设定次数"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="100">
          </el-table-column>
          <el-table-column
            prop="END_COUNT"
            label="完成次数"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="100">
          </el-table-column>
          <el-table-column
            prop="Postion"
            label="站址"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="180">
          </el-table-column>
          <el-table-column
            prop="MEMO"
            label="备注"
            align="center"
            fixed="left"
            sortable="custom"
            min-width="180">
          </el-table-column>
        </el-table> 
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        theight:window.innerHeight-202,
        metype:[ 
        {
          lable:'所有站点',
          value:'0',
        },
        {
          lable:'标准断面',
          value:'1',
        },
        {
          lable:'巴歇尔槽',
          types:'2',
        },
        {
          lable:'水闸',
          value:'3',
        },],
        tabledata:
        [
          {
            ROWID:'1',
            STNM:'钱家坪站',
            Canal_Name:'钱家坪支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄土店镇',
            MEMO:'',
          },
          {
            ROWID:'2',
            STNM:'凉水渠首站',
            Canal_Name:'凉水干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄土店镇',
            MEMO:'',
          },
          {
            ROWID:'3',
            STNM:'团岭渠首站',
            Canal_Name:'团岭干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄土店镇',
            MEMO:'',
          },
          {
            ROWID:'4',
            STNM:'唐家铺渠首站',
            Canal_Name:'唐家铺支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'谢家铺镇',
            MEMO:'',
          },
          {
            ROWID:'5',
            STNM:'草坪渠首站',
            Canal_Name:'草坪支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'谢家铺镇',
            MEMO:'',
          },
          {
            ROWID:'6',
            STNM:'东干渠首站',
            Canal_Name:'东干支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'许家桥回族维吾尔族乡',
            MEMO:'',
          },
          {
            ROWID:'7',
            STNM:'南阳渠首站',
            Canal_Name:'南阳支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'尧天坪镇',
            MEMO:'',
          },
          {
            ROWID:'8',
            STNM:'羊耳岗渠首',
            Canal_Name:'羊耳岗支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'尧天坪镇',
            MEMO:'',
          },
          {
            ROWID:'9',
            STNM:'肖家坪渡槽',
            Canal_Name:'超美干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },
          {
            ROWID:'10',
            STNM:'新安冲渠首站',
            Canal_Name:'新安冲支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },
          {
            ROWID:'11',
            STNM:'红日渠首站',
            Canal_Name:'红日支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },
          {
            ROWID:'12',
            STNM:'西干渠首台',
            Canal_Name:'西干支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },
          {
            ROWID:'13',
            STNM:'沙溪坪渠首站',
            Canal_Name:'沙溪坪支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },
          {
            ROWID:'14',
            STNM:'火田坪渠首站',
            Canal_Name:'火田坪支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'草坪镇',
            MEMO:'',
          },
          {
            ROWID:'15',
            STNM:'金刚河渠首站',
            Canal_Name:'金刚河支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'许家桥回族维吾尔族乡',
            MEMO:'',
          },
          {
            ROWID:'16',
            STNM:'谢家铺渠首站',
            Canal_Name:'谢家铺干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'石门桥镇',
            MEMO:'',
          },
          {
            ROWID:'17',
            STNM:'石门桥渠首站',
            Canal_Name:'石门桥干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'石门桥镇',
            MEMO:'',
          },
          {
            ROWID:'18',
            STNM:'陡坡流量站',
            Canal_Name:'陡坡支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'尧天坪镇',
            MEMO:'',
          },
          {
            ROWID:'19',
            STNM:'凉水平衡站',
            Canal_Name:'凉水干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄土店镇',
            MEMO:'',
          },
          {
            ROWID:'20',
            STNM:'孙家冲平衡站',
            Canal_Name:'孙家冲干渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'黄土店镇',
            MEMO:'',
          },
          {
            ROWID:'21',
            STNM:'党家庵平衡站',
            Canal_Name:'党家庵支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },
          {
            ROWID:'22',
            STNM:'金耳冲渠首站',
            Canal_Name:'金耳冲支渠',
            ME_TYPE:'标准断面',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'许家桥回族维吾尔族乡',
            MEMO:'',
          },
          {
            ROWID:'23',
            STNM:'英雄渠首站',
            Canal_Name:'英雄支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'许家桥回族维吾尔族乡',
            MEMO:'',
          },        
          {
            ROWID:'24',
            STNM:'姥姥窝渠首站',
            Canal_Name:'姥姥窝支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'许家桥回族维吾尔族乡',
            MEMO:'',
          },               
          {
            ROWID:'25',
            STNM:'大坪渠首站',
            Canal_Name:'大坪支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'石门桥镇',
            MEMO:'',
          },
          {
            ROWID:'26',
            STNM:'阮家冲渠首站',
            Canal_Name:'阮家冲支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'石门桥镇',
            MEMO:'',
          },          
          {
            ROWID:'27',
            STNM:'徐家冲站',
            Canal_Name:'徐家冲支渠',
            ME_TYPE:'巴歇尔槽',
            RS_COUNT:'12',
            END_COUNT:'',
            Postion:'花岩溪镇',
            MEMO:'',
          },                    
        ],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
  }
</script>