<template>
  <div>
	<Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col>
          <Input search enter-button suffix="ios-search" placeholder="请输入站名：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="form.searchmsg" />
        </Col>
        <Col>
          <Button type="primary" style="width: auto;margin-right: 20px;" @click="exportToExcel">导出</Button>
        </col>
      </Row>
      <Row class="fgline"></Row>
      <el-table
        :data="data"
        border
        height="400"
        v-loading="loading"
        style="width: 100%"
        @cell-click="cellclick"
        @sort-change="sort_change">
         <el-table-column
          label=" "
          prop="ROWID"
          align="center"
          width="65"
          fixed>
        </el-table-column>
        <el-table-column
           prop="STNM"
           label="站名"
           align="center"
           fixed
           sortable="custom"
           min-width="150">
        </el-table-column>
        <el-table-column label="III级预警（黄色）" align="center">
          <el-table-column
            prop="PTD_P3"
            label="前72H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="OH_P3"
            label="1H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="TH_P3"
            label="3H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="SH_P3"
            label="6H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="TWH_P3"
            label="12H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="OD_P3"
            label="24H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
        </el-table-column>
        <el-table-column label="II级预警（橙色）" align="center">
          <el-table-column
            prop="PTD_P2"
            label="前72H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="OH_P2"
            label="1H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="TH_P2"
            label="3H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="SH_P2"
            label="6H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="TWH_P2"
            label="12H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="OD_P2"
            label="24H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
        </el-table-column>
        <el-table-column label="I级预警（红色）" align="center">
          <el-table-column
            prop="PTD_P1"
            label="前72H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="OH_P1"
            label="1H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="TH_P1"
            label="3H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="SH_P1"
            label="6H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="TWH_P1"
            label="12H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
          <el-table-column
            prop="OD_P1"
            label="24H"
            align="center"
            sortable="custom"
            min-width="90">
          </el-table-column>
        </el-table-column>
      </el-table>
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        tableheight:'',
        data:[],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
    methods:{
      exportToExcel() {
              return;
              window.location.href='/'+this.$WarmTable+'/excel/exporttarget/1';
             },
    }
  }
</script>
