<template>
  <div>
    <Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col align="left" fixed="left">
          <Input search enter-button suffix="ios-search" placeholder="请输入站名：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="form.searchmsg" />
        </Col>
      </Row>
      <Row class="fgline"></Row>
      <el-table
        :data="tabledata"
        border
        :height="theight"
        v-loading="loading"
        style="width: 100%"
        @cell-click="cellclick"
        @sort-change="sort_change">
        <el-table-column
          label=" "
          prop="ROWID"
          align="center"
          width="60"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="站名"
          prop="STNM"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="渠道"
          prop="CANAL_CODE"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="断面类型"
          prop="TYPES"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="年 份"
          prop="YR"
          align="center"
          min-width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="渠底宽度"
          prop="B"
          align="center"
          min-width="100"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="边坡系数"
          prop="M"
          align="center"
          min-width="100"
          fixed="left">          
        </el-table-column>
        <el-table-column
          label="糙率"
          prop="N"
          align="center"
          min-width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="底坡"
          prop="I"
          align="center"
          min-width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="最大水深"
          prop="MAX_Z"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="最大流量"
          prop="MAX_Q"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
      </el-table>
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        theight:window.innerHeight-202,
        tabledata:
        [
          {
            ROWID:'1',
            STNM:'姚家台',
            CANAL_CODE:'胜溪支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'2',
            STNM:'檀树湾泵站',
            CANAL_CODE:'檀树湾支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'3',
            STNM:'南干渠首',
            CANAL_CODE:'南干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'1.5',
            M:'1',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'4',
            STNM:'北干渠首',
            CANAL_CODE:'北干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'1.5',
            M:'1',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'5',
            STNM:'毛栗站',
            CANAL_CODE:'煤衡干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'1.5',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'6',
            STNM:'九支沟站',
            CANAL_CODE:'九支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'1.5',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'7',
            STNM:'新塘站',
            CANAL_CODE:'总干渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0',
            M:'0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'8',
            STNM:'黄龙站',
            CANAL_CODE:'黄龙支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.5',
            M:'0.5556',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'9',
            STNM:'四清站',
            CANAL_CODE:'四清支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.25',
            M:'0.4167',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'10',
            STNM:'八一站',
            CANAL_CODE:'八一支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0',
            M:'0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'11',
            STNM:'青林站',
            CANAL_CODE:'青林支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0',
            M:'0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'12',
            STNM:'仁寿站',
            CANAL_CODE:'仁寿支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.25',
            M:'0.3125',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'13',
            STNM:'金塘站',
            CANAL_CODE:'金塘支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.6',
            M:'0.75',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'14',
            STNM:'P4支渠站',
            CANAL_CODE:'P4支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.9',
            M:'1',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'15',
            STNM:'P5支渠站',
            CANAL_CODE:'P5支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0',
            M:'0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'16',
            STNM:'一排支渠站',
            CANAL_CODE:'一排支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.325',
            M:'0.4643',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'17',
            STNM:'二排支渠站',
            CANAL_CODE:'二排支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.65',
            M:'0.65',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'18',
            STNM:'五支渠站',
            CANAL_CODE:'五支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'0.45',
            M:'0.5',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'19',
            STNM:'三排支渠站',
            CANAL_CODE:'三排支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'20',
            STNM:'四排支渠站',
            CANAL_CODE:'四排支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0',
            M:'0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'21',
            STNM:'砖塘流量站',
            CANAL_CODE:'砖塘支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'22',
            STNM:'陡坡流量站',
            CANAL_CODE:'陡坡支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'23',
            STNM:'南干渠首',
            CANAL_CODE:'南干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'1.5',
            M:'1',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'24',
            STNM:'太阳流量站',
            CANAL_CODE:'太阳干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'25',
            STNM:'回龙铺流量站',
            CANAL_CODE:'回龙铺支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'26',
            STNM:'天鹅流量站',
            CANAL_CODE:'天鹅支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
        ],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
  }
</script>

<style type="text/css">
  .ivu-divider-horizontal, .ivu-row 
  {
    margin-bottom: 12px;
  }
  .el-table th {  background-color: #f8f8f9;color:#515a6e;} 
  .el-table td, .el-table th { padding: 3px 0;}
  .el-table .el-table__row td {padding: 6px 0;}
  .searchcon {padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:24px;background: #fff;}
  .rowtocol .ivu-col {margin-top:12px;}
</style>