<template>
  <div>
    <Content class="searchcon">
      <Row type="flex" :gutter="16" class="rowtocol">
        <Col align="left" fixed="left">
          <Input search enter-button suffix="ios-search" placeholder="请输入站名：" style="width: auto;margin-right: 20px;" @on-search="search" v-model="form.searchmsg" />
        </Col>
      </Row>
      <Row class="fgline"></Row>
      <el-table
        :data="tabledata"
        border
        :height="theight"
        v-loading="loading"
        style="width: 100%"
        @cell-click="cellclick"
        @sort-change="sort_change">
        <el-table-column
          label=" "
          prop="ROWID"
          align="center"
          width="60"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="站名"
          prop="STNM"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="渠道"
          prop="CANAL_CODE"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="断面类型"
          prop="TYPES"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="年 份"
          prop="YR"
          align="center"
          min-width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="渠底宽度"
          prop="B"
          align="center"
          min-width="100"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="边坡系数"
          prop="M"
          align="center"
          min-width="100"
          fixed="left">          
        </el-table-column>
        <el-table-column
          label="糙率"
          prop="N"
          align="center"
          min-width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="底坡"
          prop="I"
          align="center"
          min-width="80"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="最大水深"
          prop="MAX_Z"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
        <el-table-column
          label="最大流量"
          prop="MAX_Q"
          align="center"
          min-width="120"
          fixed="left">
        </el-table-column>
      </el-table>
    </Content>
  </div>
</template>

<script type="text/javascript">
  import FilterMethods from "@/assets/commonJS/FilterMethods";
  import GetDataMethods from "@/assets/commonJS/GetDataMethods";
  export default 
  {
    data()
    {
      return{
        loading:false,
        theight:window.innerHeight-202,
        tabledata:
        [          
          {
            ROWID:'1',
            STNM:'凉水渠首站',
            CANAL_CODE:'凉水干渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'2',
            STNM:'团岭渠首站',
            CANAL_CODE:'团岭干渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'3',
            STNM:'东干渠首站',
            CANAL_CODE:'东干渠首',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'4',
            STNM:'金耳冲渠首站',
            CANAL_CODE:'金耳冲支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'5',
            STNM:'红日渠首站',
            CANAL_CODE:'红日支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'6',
            STNM:'沙溪坪渠首站',
            CANAL_CODE:'沙溪坪支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'7',
            STNM:'火田坪渠首站',
            CANAL_CODE:'火田坪支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'8',
            STNM:'金刚河渠首站',
            CANAL_CODE:'金刚河支渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'9',
            STNM:'凉水平衡站',
            CANAL_CODE:'凉水干渠',
            TYPES:'矩形',
            YR:'2019',
            B:'0.0',
            M:'0.0',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'10',
            STNM:'唐家铺渠首站',
            CANAL_CODE:'唐家铺支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'11',
            STNM:'草坪渠首站',
            CANAL_CODE:'草坪支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          
          {
            ROWID:'12',
            STNM:'南阳渠首站',
            CANAL_CODE:'南阳支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'13',
            STNM:'羊耳岗渠首站',
            CANAL_CODE:'羊耳岗支渠渠首',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          
          {
            ROWID:'14',
            STNM:'新安冲渠首站',
            CANAL_CODE:'新安冲支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          
          {
            ROWID:'15',
            STNM:'西干渠首站',
            CANAL_CODE:'西干支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },                              
          {
            ROWID:'16',
            STNM:'谢家铺渠首站',
            CANAL_CODE:'谢家铺干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'17',
            STNM:'石门桥渠首站',
            CANAL_CODE:'石门桥干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'18',
            STNM:'陡山河坝渠首站',
            CANAL_CODE:'陡山河坝支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },          
          {
            ROWID:'19',
            STNM:'孙家冲平衡站',
            CANAL_CODE:'孙家冲干渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },
          {
            ROWID:'20',
            STNM:'党家庵平衡站',
            CANAL_CODE:'党家庵支渠',
            TYPES:'梯形',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },          
          {
            ROWID:'21',
            STNM:'肖家坪渡槽站',
            CANAL_CODE:'超美干渠',
            TYPES:'U 型',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          }, 
          {
            ROWID:'22',
            STNM:'钱家坪站',
            CANAL_CODE:'钱家坪支渠',
            TYPES:'U 型',
            YR:'2019',
            B:'',
            M:'',
            N:'',
            I:'',
            MAX_Z:'',
            MAX_Q:'',
          },         
        ],
        form:{
          searchmsg:'',
        }
      }
    }, 
    mounted(){
    },
  }
</script>

<style type="text/css">
  .ivu-divider-horizontal, .ivu-row 
  {
    margin-bottom: 12px;
  }
  .el-table th {  background-color: #f8f8f9;color:#515a6e;} 
  .el-table td, .el-table th { padding: 3px 0;}
  .el-table .el-table__row td {padding: 6px 0;}
  .searchcon {padding-left:24px;padding-right:24px;padding-top:12px;padding-bottom:24px;background: #fff;}
  .rowtocol .ivu-col {margin-top:12px;}
</style>